# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/ViPyTcl/core/remote_tcl.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!lib/ViPyTcl/core/remote_tcl.proto\x12\nremote_tcl\"T\n\x06\x43ommon\x12\x0c\n\x04stat\x18\x01 \x01(\x05\x12\x10\n\x03\x65rr\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08\x65rr_info\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_errB\x0b\n\t_err_info\"j\n\nTclRequest\x12\"\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x12.remote_tcl.Common\x12\x0f\n\x07timeout\x18\x02 \x01(\x05\x12\x0b\n\x03raw\x18\x03 \x01(\x08\x12\r\n\x05\x62lock\x18\x04 \x01(\x08\x12\x0b\n\x03\x63md\x18\x05 \x01(\t\"{\n\x0bTclResponse\x12\"\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x12.remote_tcl.Common\x12\x0f\n\x07timeout\x18\x02 \x01(\x05\x12\x0b\n\x03raw\x18\x03 \x01(\x08\x12\r\n\x05\x62lock\x18\x04 \x01(\x08\x12\x0b\n\x03\x63md\x18\x05 \x01(\t\x12\x0e\n\x06output\x18\x06 \x01(\t\"w\n\x0ePutFileRequest\x12\"\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x12.remote_tcl.Common\x12\x10\n\x08src_path\x18\x03 \x01(\t\x12\x10\n\x08\x64st_path\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\x0c\"g\n\x0fPutFileResponse\x12\"\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x12.remote_tcl.Common\x12\x10\n\x08src_path\x18\x03 \x01(\t\x12\x10\n\x08\x64st_path\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x05\"X\n\x0eGetFileRequest\x12\"\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x12.remote_tcl.Common\x12\x10\n\x08src_path\x18\x02 \x01(\t\x12\x10\n\x08\x64st_path\x18\x03 \x01(\t\"x\n\x0fGetFileResponse\x12\"\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x12.remote_tcl.Common\x12\x10\n\x08src_path\x18\x03 \x01(\t\x12\x10\n\x08\x64st_path\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\x0c\x32\xd3\x01\n\tRemoteTcl\x12\x38\n\x03tcl\x12\x16.remote_tcl.TclRequest\x1a\x17.remote_tcl.TclResponse\"\x00\x12\x45\n\x08get_file\x12\x1a.remote_tcl.GetFileRequest\x1a\x1b.remote_tcl.GetFileResponse\"\x00\x12\x45\n\x08put_file\x12\x1a.remote_tcl.PutFileRequest\x1a\x1b.remote_tcl.PutFileResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lib.ViPyTcl.core.remote_tcl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMON']._serialized_start=49
  _globals['_COMMON']._serialized_end=133
  _globals['_TCLREQUEST']._serialized_start=135
  _globals['_TCLREQUEST']._serialized_end=241
  _globals['_TCLRESPONSE']._serialized_start=243
  _globals['_TCLRESPONSE']._serialized_end=366
  _globals['_PUTFILEREQUEST']._serialized_start=368
  _globals['_PUTFILEREQUEST']._serialized_end=487
  _globals['_PUTFILERESPONSE']._serialized_start=489
  _globals['_PUTFILERESPONSE']._serialized_end=592
  _globals['_GETFILEREQUEST']._serialized_start=594
  _globals['_GETFILEREQUEST']._serialized_end=682
  _globals['_GETFILERESPONSE']._serialized_start=684
  _globals['_GETFILERESPONSE']._serialized_end=804
  _globals['_REMOTETCL']._serialized_start=807
  _globals['_REMOTETCL']._serialized_end=1018
# @@protoc_insertion_point(module_scope)
